apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    app: nginx 
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    - containerPort: 443

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: backend-team
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: backend
  template: 
    metadata:
      labels: 
        app: backend
    spec:
      containers:
        - name: backend
          image: sayandeep06/backend-pg:2
          ports:
            - containerPort: 3000